name: Build Android Only

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: main
      version:
        description: PDFium version
        required: false
        default: ""
      enable_v8:
        description: Enable V8
        type: boolean
        required: false
        default: false
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false

permissions:
  contents: read
  actions: write

jobs:
  build-android-arm:
    name: Android arm
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}

  build-android-arm64:
    name: Android arm64
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm64
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}

  build-android-x64:
    name: Android x64
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x64
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}

  build-android-x86:
    name: Android x86
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x86
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
